# Generated by Django 4.0.3 on 2022-03-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='char',
            new_name='name',
        ),
    ]
