# Generated by Django 4.0.3 on 2022-03-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_char_student_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-price'], 'verbose_name': 'Student'},
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Preparatory', 'Preparatory'), ('Secondary', 'Secondary')], default='hababshy', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='hababshy', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value in EGP'),
        ),
    ]
