# Generated by Django 4.0.3 on 2022-03-17 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_options_student_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='createdIn',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='student',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('Primary', 'ebteda2y'), ('Preparatory', 'Preparatory'), ('Secondary', 'Secondary')], default='hababshy', max_length=50),
        ),
    ]
