# Generated by Django 4.0.3 on 2022-03-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_createdin_student_date_student_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to=' photos/%y/%m/%d'),
        ),
    ]
